sudo: required
language: cpp
dist: trusty

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.5
    packages:
    - clang-3.5
    - g++-4.9

before_script:
    - sudo apt-get update
    - sudo apt-get install libsfml-dev cmake -y
script: 
    - mkdir build && cd build/
    - cmake ..
    - make -j
