language: cpp
dist: jessy
compiler:
  - clang++
before_script:
    - wget http://www.sfml-dev.org/files/SFML-2.1-linux-gcc-64bits.tar.bz2 --no-check-certificate -O /tmp/sfml.tar.bz2
    - tar -xjvf /tmp/sfml.tar.bz2
    - sudo cp -r SFML-2.1/* /usr/
    - sudo apt-get update
    - sudo apt-get install -y libjpeg62-dev libsndfile1-dev libglew1.5 libglew1.5-dev libfreetype6 libjpeg-turbo8 libjpeg8 libopenal-data libopenal1  libxrandr2 libxrender1 libsoil1 astyle cppcheck
script: make
