language: cpp
dist: trusty
compiler: clang++
before_script:
    - sudo apt-get update
    - sudo apt-get install libsfml-dev cmake -y
script: 
    - mkdir build && cd build/
    - cmake ..
    - make -j
